### ISSUE TITLE
[CR] [SV] DropItemDestruct Not Fired on Interact

### ISSUE THREAD

**Issue by Zidane** [AlmuraDev/Skills#7]
@gabizou made a branch here:

https://github.com/SpongePowered/SpongeCommon/commit/77b43951155b84b10d1536f736b2b4d29b03e032#diff-1be6ec3f0afa6c30d8a836137a548445R593

**Comment by Zidane** [comment]
@gabizou has pushed this to stable-7.

**Comment by gabizou** [comment]
Note that there's currently some issues I'm investigating for a random reason where entity captures aren't actually initialized, but that migration is going to take a while to correct all the phase states to move to the new logic, so this might crop back up but I'm intending to prevent it since there's a new test plugin that specifically tests for this.
